# Default values for iter8-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: iter8/iter8-controller
  tag: stable
  pullPolicy: Always

namespace: iter8
