# Default values for iter8-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name to be used when creating Kubernetes resources
name: iter8-controller

# Namespace where controller should be executed
namespace: iter8

# number of instances of controller that should be started
replicaCount: 1

# image to be used
image:
  repository: iter8/iter8-controller
  tag: v1.0.0
  pullPolicy: Always

# optional limits/requirements on needed resources
resources:
  limits:             
    cpu: 100m
    memory: 75Mi
  requests:
    cpu: 100m
    memory: 50Mi

# Version of Istio telemetry
istioTelemetry: v2
# Prometheus job label
# prometheusJobLabel: istio-mesh  # when istioTelemetry: v1
# prometheusJobLabel: envoy-stats # when istioTelemtry: v2 and Istio version < 1.7.0
prometheusJobLabel: kubernetes-pods # when Istio version >= 1.7.0

# Optional restrictions on target node(s)
nodeSelector: {}
tolerations: []
affinity: {}
