language: go
sudo: required
go:
  - "1.12"
services:
  - docker

go_import_path: github.com/iter8-tools/iter8-controller/

before_install:
  - ./test/scripts/tools.sh

script:
  - go test ./test/.
  - ./test/e2e/e2e.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export IMG="iter8/iter8-controller:$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT";
      echo "Building Docker image - $IMG";
      echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin;
      make docker-build;
      make docker-push;
    fi
