language: go
go:
  - "1.12"

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"

# Define yaml anchor to be reused across testing matrix
_end_to_end_script: &end_to_end_script
  if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
  script:
    - test/e2e/install-minikube.sh
    - test/e2e/sanity-check.sh
    - test/e2e/install-istio.sh
    - test/e2e/install-iter8.sh
    - test/e2e/e2e-test.sh

jobs:
  include:
    - stage: "unit tests"
      go_import_path: github.com/iter8-tools/iter8-controller/
      before_install:
        - ./test/scripts/tools.sh
      if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
      script:
        - go test ./test/.
    - stage: "end-to-end tests"
      env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.5.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.6.3
      <<: *end_to_end_script
    - stage: "build image"
      if: (type = push) AND (branch = master OR branch =~ /^v[0-9]+\.[0-9]+$/)
      script:
        - test/e2e/build-image.sh
