language: go
go:
  - "1.12"

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"

# Define yaml anchor to be reused across testing matrix
_end_to_end_script: &end_to_end_script
  script:
    - git clone https://github.com/iter8-tools/iter8-trend.git
    - iter8-trend/test/install-minikube.sh
    - iter8-trend/test/sanity-check.sh
    - iter8-trend/test/install-istio.sh
    #- test/e2e/e2e.sh
    - test/e2e/install-iter8.sh
    - test/e2e/e2e-test.sh

jobs:
  include:
    - stage: "unit tests"
      go_import_path: github.com/iter8-tools/iter8-controller/
      before_install:
        - ./test/scripts/tools.sh
      script:
        - go test ./test/.
    - stage: "end-to-end tests"
      env: KUBE_VERSION=v1.15.10 ISTIO_VERSION=1.4.3
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.15.10 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.16.0 ISTIO_VERSION=1.4.3
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.16.0 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - stage: "build image"
      script:
        - test/e2e/build-image.sh
