language: go
go:
  - "1.12"

stages:
  - "unit tests"

jobs:
  include:
    - stage: "unit tests"
      go_import_path: github.com/iter8-tools/iter8-controller/
      before_install:
        - ./test/scripts/tools.sh
      script:
        - go test ./test/.
