{
 "title": "Iter8 Metrics",
 "description": "Metrics Relevant to Iter8 Experiments",
 "tags": [ "iter8" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(istio_requests_total{destination_service_namespace='$namespace', destination_service_name != 'unknown'}, destination_service_name)"
   },
   {
    "name": "baseline",
    "label": "Baseline",
    "query": "label_values(istio_requests_total{destination_service_name = '$service', destination_service_namespace='$namespace', destination_workload != 'unknown'}, destination_workload)"
   },
   {
    "name": "candidate",
    "label": "Candidate",
    "query": "label_values(istio_requests_total{destination_service_name = '$service', destination_service_namespace = '$namespace', destination_workload != 'unknown'}, destination_workload)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(istio_requests_total{destination_service_namespace!='unknown'}, destination_service_namespace)"
   },
   {
    "name": "window_size",
    "label": "Window Size",
    "query": "30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "graph",
   "description": "Request rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests per sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter='source'}[$window_size]))",
     "legendFormat": "$baseline"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter='source'}[$window_size]))",
     "legendFormat": "$candidate"
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "mean latency (ms)" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_request_duration_milliseconds_sum{job='envoy-stats', destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) / sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter = 'source'}[$window_size]))",
     "legendFormat": "$baseline"
    },
    {
     "expr": "sum(increase(istio_request_duration_milliseconds_sum{job='envoy-stats', destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) / sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter = 'source'}[$window_size]))",
     "legendFormat": "$candidate"
    }
   ]
  },
  {
   "title": "Latency percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$baseline-25%"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$candidate-25%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$baseline-50%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$candidate-50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$baseline-75%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$candidate-75%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$baseline-95%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter='source'}[$window_size])) by (le))",
     "legendFormat": "$candidate-95%"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    {
     "format": "short",
     "label": "Fraction of requests with status 5**"
    }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter = 'source', response_code =~ \"5..\"}[$window_size])) / sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter = 'source'}[$window_size]))",
     "legendFormat": "$baseline"
    },
    {
     "expr": "sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter = 'source', response_code =~ \"5..\"}[$window_size])) / sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter = 'source'}[$window_size]))",
     "legendFormat": "$candidate"
    }
   ]
  },
  {
   "title": "Error counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    {
     "format": "short",
     "label": "Number of requests with status 5**"
    }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[baseline]]', destination_service_namespace='$namespace', reporter = 'source', response_code =~ \"5..\"}[$window_size]))",
     "legendFormat": "$baseline"
    },
    {
     "expr": "sum(increase(istio_requests_total{job='envoy-stats', destination_workload=~'[[candidate]]', destination_service_namespace='$namespace', reporter = 'source', response_code =~ \"5..\"}[$window_size]))",
     "legendFormat": "$candidate"
    }
   ]
  },
  { "title": "Utilization Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Utilization ($window_size)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "CPU changes per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$baseline.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$baseline}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$candidate.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$candidate}}"
    }
   ]
  },
  {
   "title": "Memory Usage of Working Set ($window_size)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Bytes Used per second" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(container_memory_working_set_bytes{pod=~\"$baseline.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$baseline}}"
    },
    {
     "expr": "sum(avg_over_time(container_memory_working_set_bytes{pod=~\"$candidate.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$candidate}}"
    }
   ]
  },
  {
   "title": "Network Bytes Received ($window_size)",
   "type": "graph",
   "description": "Container selector does not apply here",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Bytes Received Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$baseline.*\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$baseline}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$candidate.*\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$candidate}}"
    }
   ]
  },
  {
   "title": "Network Bytes Sent ($window_size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Bytes Transmitted Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$baseline.*\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$baseline}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$candidate.*\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$candidate}}"
    }
   ]
  },
  {
   "title": "Disk Bytes Read ($window_size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Bytes Read Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$baseline.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$baseline}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$candidate.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$candidate}}"
    }
   ]
  },
  {
   "title": "Disk Bytes Written ($window_size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Bytes Per Second Written" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$baseline.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$baseline}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$candidate.*\", container!~\"istio-proxy\", namespace=\"$namespace\", image=~\".+\"}[$window_size]))",
     "legendFormat": "{{$candidate}}"
    }
   ]
  }
 ]
}