apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: {{ .Values.namespace }}
data:
  counter_metrics.yaml: |-
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($version_labels)
    - name: iter8_total_latency
      {{- if eq .Values.istioTelemetry "v2" }}
      query_template: sum(increase(istio_request_duration_milliseconds_sum{reporter='source'}[$interval])) by ($version_labels)
      units: ms # optional
      {{- else }}
      query_template: sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval])) by ($version_labels)
      units: s # optional
      {{- end }}
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($version_labels)
      preferred_direction: lower
    - name: conversion_count
      query_template: sum(increase(newsletter_signups[$interval])) by ($version_labels)
  # the value of a ratio metric equals value of numerator divided by denominator
  ratio_metrics.yaml: |-
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denominator: iter8_request_count
      preferred_direction: lower
    - name: iter8_error_rate
      numerator: iter8_error_count
      denominator: iter8_request_count
      preferred_direction: lower
      zero_to_one: true
    - name: conversion_rate
      numerator: conversion_count
      denominator: iter8_request_count
      preferred_direction: higher
      zero_to_one: true
