apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: {{ .Values.namespace }}
data:
  # by convention, metrics with names beginning with iter8_ are defined by iter8
  # a counter metric is monotonically increasing or decreasing
  counter_metrics.yaml: |-
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source',job='{{ .Values.prometheusJobLabel}}'}[$interval])) by ($version_labels)
    - name: iter8_total_latency
      {{- if eq .Values.istioTelemetry "v2" }}
      query_template: sum(increase(istio_request_duration_milliseconds_sum{reporter='source',job='{{ .Values.prometheusJobLabel}}'}[$interval])) by ($version_labels)
      {{- else }}
      query_template: (sum(increase(istio_request_duration_seconds_sum{reporter='source',job='{{ .Values.prometheusJobLabel}}'}[$interval])) by ($version_labels))*1000
      {{- end }}
      units: msec
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source',job='{{ .Values.prometheusJobLabel}}'}[$interval])) by ($version_labels)
      preferred_direction: lower
  # the value of a ratio metric equals value of numerator divided by denominator
  ratio_metrics.yaml: |-
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denominator: iter8_request_count
      preferred_direction: lower
      units: msec
    - name: iter8_error_rate
      numerator: iter8_error_count
      denominator: iter8_request_count
      preferred_direction: lower
      zero_to_one: true
