apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: iter8
data:
  # by convention, metrics with names beginning with iter8_ are defined by iter8
  # a counter metric is monotonically increasing or decreasing
  counter_metrics.yaml: |-
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source',job='istio-mesh'}[$interval])) by ($version_labels)
    - name: iter8_total_latency
      query_template: (sum(increase(istio_request_duration_milliseconds_sum{reporter='source',job='istio-mesh'}[$interval])) by ($version_labels))*1000
      units: msec # optional
      preferred_direction: lower
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source',job='istio-mesh'}[$interval])) by ($version_labels)
      preferred_direction: lower
    - name: books_purchased_total
      query_template: sum(increase(number_of_books_purchased_total{}[$interval])) by ($version_labels)
      preferred_direction: higher
    - name: 500_ms_latency_percentile
      query_template: (sum(increase(istio_request_duration_milliseconds_bucket{le='500', job='istio-mesh', reporter="source"}[$interval])) by ($version_labels))
      preferred_direction: higher
    - name: latency_percentile_total
      query_template: (sum(increase(istio_request_duration_milliseconds_bucket{le="10000", job='istio-mesh', reporter="source"}[$interval])) by ($version_labels))
  # the value of a ratio metric equals value of numerator divided by denominator
  ratio_metrics.yaml: |-
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denominator: iter8_request_count
      preferred_direction: lower
    - name: iter8_error_rate
      numerator: iter8_error_count
      denominator: iter8_request_count
      preferred_direction: lower
      zero_to_one: true
    - name: mean_books_purchased
      numerator: books_purchased_total
      denominator: iter8_request_count
      preferred_direction: higher
    - name: mean_500_ms_latency_percentile
      numerator: 500_ms_latency_percentile
      denominator: latency_percentile_total
      preferred_direction: higher
