apiVersion: v1
kind: ConfigMap
metadata:
  name: iter8config-metrics
  namespace: iter8
  annotations:
    version: 1.0.0 # metric spec version
data: # by convention, metrics with names beginning with iter8_ are defined by iter8
  # a counter metric is monotonically increasing or decreasing
  counter_metrics.yaml: |-
    - name: iter8_request_count
      query_template: sum(increase(istio_requests_total{reporter='source'}[$interval])) by ($version_labels)
    - name: iter8_total_latency
      query_template: sum(increase(istio_request_duration_seconds_sum{reporter='source'}[$interval])) by ($version_labels)
      units: msec # optional
    - name: iter8_error_count
      query_template: sum(increase(istio_requests_total{response_code=~'5..',reporter='source'}[$interval])) by ($version_labels)
      preferred_direction: lower # preferred_direction must be specified in order to use thresholds
    - name: books_purchased_total
      query_template: sum(increase(number_of_books_purchased_total{}[$interval])) by ($version_labels)
      preferred_direction: higher
    - name: 500_ms_latency_percentile
      query_template: (sum(increase(istio_request_duration_milliseconds_bucket{le='500', job='envoy-stats', reporter="source"}[$interval])) by ($version_labels))
      preferred_direction: higher
    - name: latency_percentile_total
      query_template: (sum(increase(istio_request_duration_milliseconds_bucket{le="10000", job='envoy-stats', reporter="source"}[$interval])) by ($version_labels))
  # the value of a ratio metric equals value of numerator divided by denominator
  ratio_metrics.yaml: |-
    - name: iter8_mean_latency
      numerator: iter8_total_latency
      denominator: iter8_request_count
      preferred_direction: lower # lower mean latency is preferable to higher mean latency
    - name: iter8_error_rate
      numerator: iter8_error_count
      denominator: iter8_request_count
      preferred_direction: lower
      zero_to_one: true # metric is always between 0 and 1
    - name: mean_books_purchased
      numerator: books_purchased_total
      denominator: iter8_request_count
      preferred_direction: higher
    - name: mean_500_ms_latency_percentile
      numerator: 500_ms_latency_percentile
      denominator: latency_percentile_total
      preferred_direction: higher
