apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: productpage-abn-test
spec:
  service:
    name: productpage
    baseline: productpage-v1
    candidates:
      - productpage-v2
      - productpage-v3
    routingReference:
      apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      name: bookinfo
  criteria:
    - metric: iter8_mean_latency
      threshold:
        type: absolute
        value: 1500
    # - metric: iter8_mean_latency
    #   threshold:
    #     type: relative
    #     value: 1.6
    - metric: iter8_error_rate
      threshold:
        type: absolute
        value: 0.05
    - metric: 500_ms_latency_percentile
      threshold:
        type: absolute
        value: 0.99
    - metric: mean_books_purchased
      isReward: true
  duration:
    interval: 20s
    maxIterations: 20
  trafficControl:
    strategy: progressive
    percentage: 80
    maxIncrement: 25
