apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v3
  labels:
    app: productpage
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: productpage
        version: v3
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: iter8/productpage:demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
          - name: deployment
            value: "productpage-v3"
          - name: namespace
            value: "bookinfo-iter8"
          - name: color
            value: "green"
          - name: reward_min
            value: "10"
          - name: reward_max
            value: "20"
          - name: port
            value: "9082"
---
