apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v5-rollout
spec:
  service:
    name: reviews
    baseline: reviews-v3
    candidates: [ "reviews-v5" ]
  criteria:
    - metric: iter8_mean_latenecy
      threshold:
        type: absolute
        value: 200 # milliseconds
    - metric: iter8_error_rate
      threshold:
        type: relative
        value: 1.02
        cutoffTrafficOnViolation: true
  duration:
    interval: 30s
    maxIterations: 8
  trafficControl:
    percentage: 100
    maxIncrement: 100
  cleanup: true