apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: productpage-v2-rollout
spec:
  service:
    name: productpage
    baseline: productpage-v1
    candidates: [ "productpage-v2" ]
  routingReference:
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    name: bookinfo
  criteria:
    - metric: iter8_mean_latenecy
      threshold:
        type: absolute
        value: 300 # milliseconds
  duration:
    interval: 30s
    maxIterations: 8
  trafficControl:
    percentage: 100
    maxIncrement: 100
  cleanup: true