apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: productpage
        version: v2
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: iter8/examples-bookinfo-productpage:iter8-v2
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v2"

