apiVersion: iter8.tools/v1alpha1
kind: Experiment
metadata:
  name: productpage-v2-rollout
spec:
  routingReference:
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    name: bookinfo
  targetService:
    name: productpage
    apiVersion: v1
    baseline: productpage-v1
    candidate: productpage-v2
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 20
    maxIterations: 6
    maxTrafficPercentage: 80
  analysis:
    analyticsService: "http://iter8-analytics.iter8"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 3.0
        sampleSize: 5
