apiVersion: iter8.tools/v1alpha1
kind: Experiment
metadata:
  name: reviews-v5-rollout
spec:
  targetService:
    name: reviews
    apiVersion: v1
    baseline: reviews-v3
    candidate: reviews-v5
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 20
    maxIterations: 6
    maxTrafficPercentage: 80
  analysis:
    analyticsService: "http://iter8-analytics:8080"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 200
        sampleSize: 5
      - metricName: iter8_error_rate
        toleranceType: delta
        tolerance: 0.02
        sampleSize: 10
        stopOnFailure: true
